// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0xLc5RI3Z15DRReyuHbNWpoQPjQb2sU',
    appId: '1:827635554587:web:d4b3ba1e5b2399cae55bbe',
    messagingSenderId: '827635554587',
    projectId: 'simplecrud-5d146',
    authDomain: 'simplecrud-5d146.firebaseapp.com',
    storageBucket: 'simplecrud-5d146.appspot.com',
    measurementId: 'G-DJ5F09K39H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5_eoq0cfzoCgixPB1RroVWzOiJEbnmec',
    appId: '1:827635554587:android:11a83df24af64c99e55bbe',
    messagingSenderId: '827635554587',
    projectId: 'simplecrud-5d146',
    storageBucket: 'simplecrud-5d146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfLq3bkL2WOXfObm4e0ZDQauBzdlBcXGU',
    appId: '1:827635554587:ios:906e2e577b099f24e55bbe',
    messagingSenderId: '827635554587',
    projectId: 'simplecrud-5d146',
    storageBucket: 'simplecrud-5d146.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
